# Generated by Django 3.1.3 on 2020-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('elo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
