# Generated by Django 3.1.3 on 2020-12-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loser_player', models.ManyToManyField(related_name='loser', to='elo_admin.Player')),
                ('winner_player', models.ManyToManyField(related_name='winner', to='elo_admin.Player')),
            ],
        ),
    ]
