# Generated by Django 3.1.3 on 2020-12-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo_admin', '0002_auto_20201214_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser_player',
        ),
        migrations.AddField(
            model_name='match',
            name='loser_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to='elo_admin.player'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_player',
        ),
        migrations.AddField(
            model_name='match',
            name='winner_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='elo_admin.player'),
        ),
    ]
